name: Build IPA

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        run: |
          echo "CI=true" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          brew update
          brew install ldid make

      - name: Inspect project
        run: |
          xcodebuild -version
          xcodebuild -list -project darksword-kexploit-fun.xcodeproj

      - name: Build archive
        run: |
          xcodebuild \
            -project darksword-kexploit-fun.xcodeproj \
            -scheme darksword-kexploit-fun \
            -configuration Release \
            -archivePath build/app.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            archive

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: darksword-build
          path: build/app.xcarchive
